version: '3.8'
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dc-school
      - POSTGRES_DB=dc-school
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  db:
    image: postgres:13.7-alpine
    container_name: dc-school-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=dc-school
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root